database: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV['DB_POOL'] %>
  strict: false

development:
  <<: *default

test:
  <<: *default
  database: app_test

staging:
  <<: *default

production:
  <<: *default